OWNER = "vagrant"

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"
  config.vm.boot_timeout = 400
  config.vm.synced_folder "./../Course_files", "/opt/Course_files"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096
    vb.cpus = 3
    vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
    vb.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
  end

  config.vm.provision "shell", path: "./../install_dockerEngine.sh", args: "#{OWNER}"
  config.vm.provision "shell", path: "./../install_kubectl.sh"
  config.vm.provision "shell", path: "./../install_microk8s.sh", args: "#{OWNER}"
  config.vm.provision "shell", path: "./../install_additional_tools.sh"
  config.vm.provision "shell", inline: <<-SHELL
    apt install dos2unix -y
    find "/opt/Course_files" -type f -print0 | xargs -0 dos2unix
    bash /opt/Course_files/Nginx/deploy.sh
  SHELL
end
