Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"

  config.vm.boot_timeout = 420

  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.synced_folder "./../Course_files", "/home/vagrant/Course_files", disabled: false

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 3096
    vb.cpus = 3
    vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
    vb.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
  end

  config.vm.provision "shell", path: "./../install_docker_engine.sh"
  config.vm.provision "shell", path: "./../install_kubectl.sh"
  config.vm.provision "shell", path: "./../install_minikube.sh"
  config.vm.provision "shell", path: "./../install_additional_tools.sh"
end
